name: Sync Release to GitHub

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Run Releases Sync Action
        uses: https://git.0xmax42.io/actions/releases-sync@main
        with:
          gitea_token: $ACTIONS_RUNTIME_TOKEN
          gitea_url: https://git.0xmax42.io
          gitea_owner: maxp
          gitea_repo: http-kernel
          tag_name: ${{ github.event.release.tag_name }}
          github_token: ${{ secrets.SYNC_GITHUB_TOKEN }}
          github_owner: 0xMax42
          github_repo: http-kernel
